# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='liked_cmnts', to='login.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='liked_msgs', to='login.User'),
        ),
    ]
